services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v3.0
    restart: "always"
    command: 
      - "--log.level=INFO"

      - "--accesslog=true"

      - "--ping"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"

      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
      
      - "--api.dashboard=true"
      # - "--api.insecure=true"
      # - "--api.debug=true"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

      - "--providers.file.directory=/etc/traefik/config"
      
      - "--certificatesresolvers.certbot=true"
      - "--certificatesresolvers.certbot.acme.email=${EMAIL}"
      - "--certificatesresolvers.certbot.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.certbot.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"

      - "--certificatesresolvers.certbot.acme.httpchallenge=true"
      - "--certificatesresolvers.certbot.acme.httpchallenge.entrypoint=http"

      #- "--certificatesResolvers.certbot.acme.tlsChallenge=true"
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 30
    labels:
      - "traefik.enable=true"

      # redirect all http to https
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=https-only@file

      # traefik dashboard 
      - "traefik.http.routers.dashboard.middlewares=admin-auth@file"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls.certresolver=certbot"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
