version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.36.1
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - "--web.route-prefix=/"
      - "--web.external-url=https://${PROMETHEUS_URL}"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - traefik

  grafana:
    image: grafana/grafana:6.6.1
    restart: unless-stopped
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - grafana.env
    depends_on:
      - prometheus
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.middlewares=default-headers@file,admin-auth@file"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_URL}`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls.certresolver=certbot"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

volumes:
  prometheus:
  grafana:

networks:
  traefik:
    external:
      name: traefik_proxy