services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine
    ports:
      - "50000:50000"
    restart: "always"
    volumes:
      - jenkins_data:/var/jenkins_home
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_URL}`)"
      - "traefik.http.routers.jenkins.entrypoints=https"
      - "traefik.http.routers.jenkins.tls.certresolver=certbot"
      #- "traefik.http.routers.jenkins.middlewares=default-headers@file"

      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      - traefik

volumes:
  jenkins_data:
    driver: local

networks:
  traefik:
    name: traefik_proxy
    external: true
